sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.32.132
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    access-key-secret: U6K1brOZ8gaOIXv3nXbulGTUzy64
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: sky-itcast
    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
  redis:
    database: 2
    host: 192.168.32.132
    port: 6379
    password: 123456
    max-active: 8
    max-idle: 8
    min-idle: 0
    max-wait: -1ms